write_text=input("Enter text to be written in the file :")
append_text= input("Enter text to append:")
file1=open('output.txt','w')
writing=file1.write(write_text)
appending=file1.write(append_text)
file1=open('output.txt','r')
reading=file1.read()
print(reading)
file1.close()